platform :ios, '7.0'
pod 'Masonry', '0.5.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'TTTAttributedLabel', '1.10.1'
pod 'BlocksKit', '2.2.5'
pod 'TPKeyboardAvoiding', '1.2.4'
pod 'MBProgressHUD', '0.9'
pod 'ReactiveCocoa'
pod 'MJExtension', '~> 2.5.9'
pod 'Toast', '~> 2.4'